### ISSUE TITLE
choose color on edge does not work

### ISSUE THREAD

**Issue by golya** [brianpkelley/md-color-picker#1]
You can not choose color on edge, its always follow the mouse position, and if you click to a color nothing happend.

**Comment by stewones** [comment]
+1

**Comment by brianpkelley** [comment]
Can you expand on this?  Are you referring to the ~1px right hand edge?  Because this is a component in a project, and a non show stopper, progress will be slow, sorry.

**Comment by golya** [comment]
Sorry, I was wrong, I mean Microsoft Edge as a browser.

**Comment by brianpkelley** [comment]
Can you try the latest version.

**Comment by brianpkelley** [comment]
Unable to reproduce in my windows 10 with edge VM
