### ISSUE TITLE
Opening colour picker from another modal dialog

### ISSUE THREAD

**Issue by carlosngis** [brianpkelley/md-color-picker#15]
We are launching the colour picker from another modal "md-dialog"
This causes the calling dialog to be closed and we can't return to it once the colour picker has been closed

Is there any way to configure or set up the colour picker in order to work together with other modal dialogs ?

Thanks

**Comment by brianpkelley** [comment]
There is now a `$mdColorPicker` service with a show method written by @IDontEatSoap .  This may be useful for this instance.  I haven't played with it as of yet.
