### ISSUE TITLE
CMYK support

### ISSUE THREAD

**Issue by JuanHB** [brianpkelley/md-color-picker#16]
Your component is amazing! But I'm currently working in a project from a printing company and they use CMYK color pattern, I know I can convert hex to CMYK after the user picks a color, but I want to know if it's possible to show the CMYK value directly  in the component input area.

**Comment by brianpkelley** [comment]
This can be done, but I'm not sure it should be done.  Currently it it uses the three common color notations used by browsers.  It also sets the css styles to the currently selected method so there would need to be a separation of "css value" and "display value".

Potentially it could be an option thats false by default.  

I'm currently swamped so this project has taken a back seat at the moment.  Not even enough time to validate the current pull requests.

**Comment by JuanHB** [comment]
Ok, thanks for the update, I'll try and do the implementation myself, not now because I'm very busy with this project, but as soon as I get a break I'll fork and do a PR with the CMYK option.

**Comment by jkevingutierrez** [comment]
+1

**Comment by brianpkelley** [comment]
Coming in the new re-write, custom notations can be added in the .config() process of the module.

Here is a demo of a CMYK notation being added.  http://labs.tastybytes.net/mdColorPicker/demo/cmyk/
