### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by AndrewMonty** [brianpkelley/md-color-picker#17]
Hello,

Could you make sure NPM is up to date? The package page says it was last published 4 months ago, and when I installed it seems to be a few commits behind.

https://www.npmjs.com/package/md-color-picker

Thanks!

**Comment by brianpkelley** [comment]
Currently working on updating a few things and will publish a new release in a day or two.

**Comment by brianpkelley** [comment]
Pushed v0.2.1 today, sorry for the delay.
