### ISSUE TITLE
Latest AngularMaterial (1.0.3) breaks layout.

### ISSUE THREAD

**Issue by urrri** [brianpkelley/md-color-picker#25]
I tried color picker with material 1.0.3 and angular 1.4.8 and all layout becomes askew.
In both parts editor and dialog.

**Comment by roelbarreto** [comment]
Applied fix on this pull request by setting padding bottom to 0. New Angular material update added padding bottom when tab is on bottom.
https://github.com/brianpkelley/md-color-picker/pull/22
You can use my forked version for a while. https://github.com/ipiz/md-color-picker/tree/develop
I also added the icons into templatecache in case we are not using the same icon libraries.

**Comment by hpawe01** [comment]
Thanks a lot @ipiz. Can @brianpkelley please merge this pull request?

**Comment by brianpkelley** [comment]
I've merged the pull request, but haven't tested it.  Leaving this open until I get some time.

**Comment by urrri** [comment]
It breaks all totally. Not just color picker absolutely broken, but components that declared after it are now broken.
