### ISSUE TITLE
$mdDialog closes on open color picker

### ISSUE THREAD

**Issue by fabricio0915** [brianpkelley/md-color-picker#26]
When open a color picker inside a mdDialog he close his parent. Anyone has any suggestions?

**Comment by roelbarreto** [comment]
This is currently an open issue from https://github.com/angular/material/issues/3072 and https://github.com/angular/material/issues/698

**Comment by jaimeguaman** [comment]
i´m having the same issue.
an option would be to display the color picker using $mdDialog or not based on a directive's config parameter like `data-show-dialog`

**Comment by jordanchapian** [comment]
@jaimeguaman I have a similar issue open #19

**Comment by olee** [comment]
Why not just implement this in the same way like md-datepicker which works without any problems?

**Comment by brianpkelley** [comment]
When this was created, there was no md-datepicker.  You can also see that there is an "inline-dialog" branch that is being worked on. There is also substantially more functionality than scrolling and a click event.

**Comment by brianpkelley** [comment]
Please see #47 or #19
