### ISSUE TITLE
Layout is broken with Material 0.11.2

### ISSUE THREAD

**Issue by websirnik** [brianpkelley/md-color-picker#3]
I've tried md-color-picker with the latest available Angular Material 0.11.2.
Layouts in demo and md-color-picker popup are broken.
Demo: http://embed.plnkr.co/MFpIsj/

**Comment by stewones** [comment]
+1

**Comment by brianpkelley** [comment]
Looks to be caused by the breaking changes in v 0.11.0-rc1.  I will try to get the flex attributes swapped to the .flex class names pretty soon.

**Comment by websirnik** [comment]
It looks better on the latest Master of Angular-material. Still, need to align multiple elements.
http://embed.plnkr.co/QuF5ZT1aLLyB2XuglXRW/preview
