### ISSUE TITLE
Consider changing license to MIT

### ISSUE THREAD

**Issue by Frank3K** [brianpkelley/md-color-picker#34]
Both [angular.js](https://github.com/angular/angular.js/blob/master/LICENSE) and [angular-material](https://github.com/angular/material/blob/master/LICENSE) are licensed under MIT. 

 [GPL-2.0](https://tldrlegal.com/license/gnu-general-public-license-v2) requires that the source of the application in which this module is used is also made available under the GPL license. I think this will prevent a substantial group of users to use this module. The [MIT license](https://tldrlegal.com/license/mit-license) is much more permissive.

**Comment by scottmcarthur** [comment]
I agree. This looks like a nice library, but I can't use it under GPL. MIT suits Angular better.

**Comment by Frank3K** [comment]
I think the GPL license even conflicts with `angular-material` and `angular.js` itself. Since GPL requires that the code that includes GPL code (here: `md-color-picker`) is GPL, one could say that one can not use `angular-material` and `md-color-picker` together. Without `angular-material` this plugin can not be used.

**Comment by brianpkelley** [comment]
Thanks, I'm not well versed in licenses so made the change!
