### ISSUE TITLE
Angular material update (1.0.5) breaks css in header, button history and cancel button

### ISSUE THREAD

**Issue by tipodisimmia** [brianpkelley/md-color-picker#35]
This is  (http://plnkr.co/edit/hPxmahoKTKascaFTLaZg?p=preview)  a plunker  with angular material 1.0.5.
Some elements are not correctly displayed : 
- Popup: input filed, history button 
-  Field: cancel button

Thank you

**Comment by roelbarreto** [comment]
Dup https://github.com/brianpkelley/md-color-picker/issues/25
