### ISSUE TITLE
Slow dialog opening

### ISSUE THREAD

**Issue by AlexanderKozhevin** [brianpkelley/md-color-picker#39]
It's takes about a second to open the dialog. What's wrong with it?
How can I speed it up? 
![feb 12 2016 16 00](https://cloud.githubusercontent.com/assets/4464561/13007514/ebbfe24e-d1a1-11e5-8c1e-5b12a0ee16df.gif)

**Comment by jmls** [comment]
I have a similar problem

**Comment by brianpkelley** [comment]
![screen_capture_20160304-114832](https://cloud.githubusercontent.com/assets/1156538/13535338/35bf88c8-e1ff-11e5-988d-e53de862832a.gif)

**Comment by AlexanderKozhevin** [comment]
Have you fixed it?

**Comment by AlexanderKozhevin** [comment]
@brianpkelley have you fixed it?

**Comment by brianpkelley** [comment]
Yes, its been pushed to the v0.2.5 branch, but not merged into develop or master yet.

**Comment by AlexanderKozhevin** [comment]
@brianpkelley Thanx a lot!
