### ISSUE TITLE
Unknown error - Incomplete pallette, only one row

### ISSUE THREAD

**Issue by AlexanderKozhevin** [brianpkelley/md-color-picker#40]
![screen shot 2016-02-12 at 15 23 09](https://cloud.githubusercontent.com/assets/4464561/13006822/b2f39028-d19c-11e5-9c89-afb08aaf1bcc.png)

**Comment by brianpkelley** [comment]
Can you provide anymore information?  Which version of angular material are you using? Link to demo page?
