### ISSUE TITLE
Palette not shown in dialog

### ISSUE THREAD

**Issue by franjuan** [brianpkelley/md-color-picker#46]
Hi.
When dialog is loaded is seems to be everything ok, but when browsing through tabs, the palette tab seems to be empty. Debug shows that palette is created correctly from template but cell containing de colors have a 0px width value (value rendered by browser from css configuration):
![palette](https://cloud.githubusercontent.com/assets/9873247/13376638/662897da-ddc1-11e5-96b6-90bc0d585a4f.png)
If template forces a width value as does with heigh it works, line 879:
`<div ng-repeat="col in row track by $index" flex="10" style="height: 25.5px;width: 25.5px;" ng-style="{\'background\': col};" ng-click="setPaletteColor($event)"></div>' +`
But this is probably not the most elegant way to do it. It seems that flex is not working. Please, could you give some instructions to solve the problem?

Thanks.

**Comment by brianpkelley** [comment]
Which version of angular and angular material are you using?  I noticed some issues with the tabs and tab containers while working on the latest release.  Theses issues seemed be caused by using material 1.0.5 and angular 1.0.0.  After updating to angular 1.0.5 the issues resolved themselves.

**Comment by franjuan** [comment]
Hi Brian.
I am using 1.0.0 for angular material and 1.4.8 for angular. I upgraded angular material to 1.0.6 and angular to 1.5.0, but the problem persists.
The problem seems to be in the row width. As we had to define the exact height of every element in the row, we must define the exact width of the row. I use a style="width:100%" and it did the trick:
`'                      <div ng-repeat="row in palette track by $index" flex="15" style="width:100%;" layout-align="space-between" layout="row">' +`
Line 879 is kept as original.
Probably flex is not working as expected when the elements are empty.
Thank you for your help!

**Comment by brianpkelley** [comment]
There has been a new version release, can you please try v0.2.1 and let me know if it still persists.

**Comment by franjuan** [comment]
Yeah, it works perfectly!

Thank you very much!

**Comment by brianpkelley** [comment]
Great, glad that worked out for you!
