### ISSUE TITLE
$mdColorPicker: support options to keep the colorpicker from closing an open dialog

### ISSUE THREAD

**Issue by dgavigan** [brianpkelley/md-color-picker#47]
setting `preserveScope` and `skipHide` to true while opening the color picker from an open mdDialog will keep the dialog component open for a user to select a color, and return to the original dialog

**Comment by slfan2013** [comment]
Does v0.2.6 version has this problem fixed?


`<div ng-repeat="color in structure.parameters.pair_score_plot.color" md-color-picker ng-model="color.option" label="{{color.levels}}" icon="color_lens" skip-hide='true' preserve-scope='true'></div>` still close the parent dialog.
