### ISSUE TITLE
ng-model not updating by click on clear button

### ISSUE THREAD

**Issue by EugeneMoz** [brianpkelley/md-color-picker#55]
mdColorPicker.js line 482 
if (**newVal !== ''** && typeof newVal !== 'undefined' && newVal && newVal !== oldVal) {
Why did you use this in condition? This means I could never return to default background

**Comment by che85** [comment]
+1

**Comment by kudobyte** [comment]
You would also need to remove the **&& newVal** condition.

**Comment by langan** [comment]
I think I fixed this by changing line 491 from

`$scope.value = '';`

to

`ngModel.$setViewValue('');`

I've got the fix in a fork @brianpkelley if you need a PR

**Comment by brianpkelley** [comment]
@langan That would be great!  Thanks! Nevermind, I see the changes in #78
