### ISSUE TITLE
Not selecting in modal

### ISSUE THREAD

**Issue by LeVadim** [brianpkelley/md-color-picker#64]
Good day!
  This colorpicker is inactive when I put md-color-input into the modal?
It opens and seems fine, but I am not able to select any of colors, but when I close the modal it is able to select colors. **Need help.**
Do anyone have some suggestions?

Regards, Vadim.

**Comment by LeVadim** [comment]
Hey. Is there any hope to get the answer for this issue? Its really important for me.

**Comment by brianpkelley** [comment]
Do you have any demos or something I could look at to dig into this issue?

**Comment by LeVadim** [comment]
Hi. I decided to remove the modal and create the new views. This solves my problem. Thanks :)
