### ISSUE TITLE
 l.getObject is not a function

### ISSUE THREAD

**Issue by kirdua1** [brianpkelley/md-color-picker#72]
I have installed color picker and have been following your instructions on the main page. However, I was keep getting the same error for your options, more to the point at the history. 

```
$scope.navbarBgColor.options = {
        label: "Choose a color",
        icon: "brush",
        default: "#f00",
        genericPalette: false,
        history: false
      }
```

with `<div md-color-picker="navbarBgColor.options" ng-model="navbarBColor.color"></div>`. 

The error also occurs when I implement the options as an attribute of the div.

**Comment by brianpkelley** [comment]
Do you have TinyColor installed and included before angular/md-color-picker? 

Can you set up a demo with the issue as well?

**Comment by kirdua1** [comment]
I do have TinyColor installed and is called prior to md-color-picker.

**Comment by brianpkelley** [comment]
I just noticed this while going through these again.

```
ng-model="navbarBColor.color"
```
Is missing the `g` in `Bg`

fixed:
```
ng-model="navbarBgColor.color"
```

**Comment by idirMeziane** [comment]
i still have same error can you set all your code (html and "controller" Js)
