### ISSUE TITLE
Launch from a click

### ISSUE THREAD

**Issue by amritk** [brianpkelley/md-color-picker#73]
Is there any way to launch the color picker from a button instead of the input/preview?

**Comment by amritk** [comment]
Found it, cheers.

```
$mdColorPicker.show({
                        value: $scope.value,
                        defaultValue: $scope.default,
                        random: $scope.random,
                        clickOutsideToClose: $scope.clickOutsideToClose,
                        hasBackdrop: $scope.hasBackdrop,
                        skipHide: $scope.skipHide,
                        preserveScope: $scope.preserveScope,

                        mdColorAlphaChannel: $scope.mdColorAlphaChannel,
                        mdColorSpectrum: $scope.mdColorSpectrum,
                        mdColorSliders: $scope.mdColorSliders,
                        mdColorGenericPalette: $scope.mdColorGenericPalette,
                        mdColorMaterialPalette: $scope.mdColorMaterialPalette,
                        mdColorHistory: $scope.mdColorHistory,
                        mdColorHex: $scope.mdColorHex,
                        mdColorRgb: $scope.mdColorRgb,
                        mdColorHsl: $scope.mdColorHsl,
                        mdColorDefaultTab: $scope.mdColorDefaultTab,

                        $event: $event,

                    }).then(function( color ) {
                        $scope.value = color;
                    });
```

**Comment by brianpkelley** [comment]
For now that is the way.  I will be breaking up the standard "md-color-picker" template into "md-color-picker-preview" "md-color-picker-input" etc etc.  Hopefully adding a "dropdown" style as well (md-datepicker esque).

**Comment by amritk** [comment]
Awesome, sounds good. You're doing good work! This is the nicest looking color picker I've found!

**Comment by gessha** [comment]
I'm sorry, can you expand on how to call it from a button click? I'm new to Angular and still very confused. My idea is to call it from a context-menu option but when I try the code above, I get `$mdColorPicker is not defined.`

**Comment by amritk** [comment]
You need to make sure to inject $mdColorPicker into your controller, or wherever you are calling it from

**Comment by gessha** [comment]
Once you've injected it, how do you call the showColorPicker() function and how do you get the value out of it?

Again, sorry for the stupid questions.

**Comment by amritk** [comment]
```
$mdColorPicker.show(options).then(function( color: string ) {
    console.log(color)
});
```

**Comment by amritk** [comment]
Or you can also pass something into options.value which will change real time

**Comment by gessha** [comment]
I tried the function without passing anything, because I saw that it uses the defaults in that case but I get `angular.js:13708 TypeError: Cannot read property 'search' of undefined`

**Comment by amritk** [comment]
you might need to pass in the value option, it might not be optional. Just pass in any colour to test it.

**Comment by gessha** [comment]
Problem solved. Thank you!

**Comment by gessha** [comment]
This is the solution:

```
$mdColorPicker.show({
                    value:"#FFFFFF"
                }).then(function(color) {
                    console.log(color);
                });
```

**Comment by brianpkelley** [comment]
Thanks for helping out @amritk !  Glad everything got sorted out @gessha.
