### ISSUE TITLE
Working example for Angular2

### ISSUE THREAD

**Issue by jbaan** [brianpkelley/md-color-picker#90]
Hi,
I wanted to upgrade my application (having the md-color-picker) to Angular 2.0. I think I need Material Design for Angular 2.0 as well. Are there more pitfalls to take into account while upgrading? Or do you have a working example for the md-color-picker on Angular2.0?

**Comment by brianpkelley** [comment]
There is no support for angular 2.0 currently.  Sorry.  After the rewrite I may try to rework the plugin for angular 2.0 but that's not on the road map currently.
